import { Routes } from '@angular/router';
import { PeoplesComponent } from './views/peoples/peoples.component';
import { PlanetsComponent } from './views/planets/planets.component';
import { FilmsComponent } from './views/films/films.component';
import { SpeciesComponent } from './views/species/species.component';
import { StarshipsComponent } from './views/starships/starships.component';
import { VehiclesComponent } from './views/vehicles/vehicles.component';
import { PeopleInfoComponent } from './views/peoples/people-info/people-info.component';
import { InicioComponent } from './views/inicio/inicio.component';
import { FilmInfoComponent } from './views/films/film-info/film-info.component';
import { PlanetInfoComponent } from './views/planets/planet-info/planet-info.component';
import { SpecieInfoComponent } from './views/species/specie-info/specie-info.component';
import { StarshipInfoComponent } from './views/starships/starship-info/starship-info.component';
import { VehicleInfoComponent } from './views/vehicles/vehicle-info/vehicle-info.component';

export const routes: Routes = [
  { path: '', component: InicioComponent },
  { path: 'inicio', component: InicioComponent },
  { path: 'peoples', component: PeoplesComponent },
  { path: 'planets', component: PlanetsComponent },
  { path: 'films', component: FilmsComponent },
  { path: 'species', component: SpeciesComponent },
  { path: 'starships', component: StarshipsComponent },
  { path: 'vehicles', component: VehiclesComponent },
  { path: 'people/:id', component: PeopleInfoComponent },
  { path: 'planet/:id', component: PlanetInfoComponent },
  { path: 'film/:id', component: FilmInfoComponent },
  { path: 'specie/:id', component: SpecieInfoComponent },
  { path: 'starship/:id', component: StarshipInfoComponent },
  { path: 'vehicle/:id', component: VehicleInfoComponent },
];
